DATABASE_LITE = "sql-g2.db"
CREATE_QUERY_LITE = "CREATE TABLE IF NOT EXISTS dados (id INTEGER IDENTITY(1,1), valor DECIMAL, dataHora DATETIME)"
INSERT_QUERY_LITE = "INSERT INTO dados (valor, dataHora) VALUES (?, ?)"
SELECT_QUERY_LITE = "SELECT id, valor, dataHora from dados"
DELETE_QUERY_LITE = "DELETE FROM dados"

DB_HOST = "3.239.84.130"
DB_PORT = "3306"
DB_USER = "root"
DB_PASSWORD = "root"
DATABASE = "ALGAS"
CREATE_QUERY = "CREATE TABLE IF NOT EXISTS dados (id INT PRIMARY KEY AUTO_INCREMENT, valor INT, espaco INT, dataHora TIMESTAMP)"
INSERT_QUERY = "INSERT INTO dados (id, valor, espaco, dataHora) VALUES (default, %s, %s, %s)"
SELECT_QUERY = "SELECT id, valor, espaco, dataHora FROM dados"
DELETE_QUERY = "TRUNCATE dados"
DROP_QUERY = "DROP TABLE dados"